name: Test Github Actions workflow

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: cargo build
      - name: test
        run: cargo test
      - name: clippy
        run: cargo clippy